### ISSUE TITLE
Card background/layout for a PreferenceCategory

### ISSUE THREAD

**Issue by wingoku** [AndroidDeveloperLB/MaterialPreferenceLibrary#2]
How can I assign cardView as a background/layout to the Preference Activity, so that it looks like the settings app from Android Lollipop?

**Comment by AndroidDeveloperLB** [comment]
Nice question. Maybe it's better to ask on StackOverflow, but here are my points:
1. I think the best thing to do is to check the code of the settings of Android.
2. It seem they have a GridView or RecyclerView (or a special implementation of ListView) for showing the items (switch to horizontal orientation to see this.
You could copy the code of  android.preference.PreferenceActivity, and make it use one of those, instead of a ListView. There might be other ways to accomplish this.
3. each item has an icon, as opposed to what I've done. But, as I've written in the notes, it should be possible to put it.
4. each item has a divider beneath it, except for the ones above the category, which has a special divider of the cards

If you wish, you can also use a CardView for each chunk of preferences, where each CardView uses something like the "WrapPanel" UI component of WPF, which I've found 3 solutions for it here:
http://stackoverflow.com/a/10104826/878126

**Comment by AndroidDeveloperLB** [comment]
Also, if you do find a nice solution, feel free to contribute here... :)

**Comment by wingoku** [comment]
Well after posting here. I gave it a little thought and the only solution came to my mind was to create my own layout :) .I have achieved a lollipop settings looking UI. Looking at the settings code from Android might be worth the shot but it will consume alot of time to reverse engineer it. Believe me reverse engineer is very slow and painful task. However I am still working to implement ripple effects on it.

**Comment by AndroidDeveloperLB** [comment]
Where have you found the files? I might want to do it too... I'm curious.
The way I've made this library is by looking at the code of what's downloaded from the SDK manager.

**Comment by wingoku** [comment]
I haven't looked for the code because as I mentioned reverse engineering/reading through the code and making sense of it is a very painful task. However you can decompile the "settings.apk" or look inside android-framework directory in Android Repo. If I ever need to read the settings code, I'll sure mention the link here :)

**Comment by AndroidDeveloperLB** [comment]
Oh, it's not inside the folder I was looking in? Too bad.
Can you please tell me where do I get the Android repo ?
Also, please let me know how well you are doing with what you've asked about.

**Comment by wingoku** [comment]
Download some custom rom or if you have a flashable zip of any rom, you can find the settings-framework.apk in system apps folder.

**Comment by AndroidDeveloperLB** [comment]
Isn't it open source?
