### ISSUE TITLE
Its broken

### ISSUE THREAD

**Issue by Chozzle** [AndroidDeveloperLB/MaterialPreferenceLibrary#30]
Log https://jitpack.io/com/github/AndroidDeveloperLB/MaterialPreferenceLibrary/14/build.log

**Comment by AndroidDeveloperLB** [comment]
Sample seems to still work:

![image](https://user-images.githubusercontent.com/5357526/47617606-876eb680-dad1-11e8-9a22-d2429c07ee57.png)

[MaterialPreferenceLibrary.zip](https://github.com/AndroidDeveloperLB/MaterialPreferenceLibrary/files/2522864/MaterialPreferenceLibrary.zip)

Can you please show a minimal project to demonstrate your issue?

Also, note that this library doesn't have much point anymore, and I've stopped using it, because Google already provides a decent solution, using [PreferenceFragmentCompat](https://developer.android.com/reference/android/support/v7/preference/PreferenceFragmentCompat)
