### ISSUE TITLE
Upload to maven repo

### ISSUE THREAD

**Issue by fython** [AndroidDeveloperLB/MaterialPreferenceLibrary#4]
This library is really nice but I found that I cannot use it via Maven repo.
I hope this library can be uploaded to maven repo. It will be easier for developers to use.

**Comment by AndroidDeveloperLB** [comment]
How do I do this?

**Comment by fython** [comment]
Well.... In fact, I haven't tried to do this, too.
Here is a possible way: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by jitpack-io** [comment]
Hi!

Easy to publish on JitPack:) In fact MaterialPreferenceLibrary is already there: https://jitpack.io/#AndroidDeveloperLB/MaterialPreferenceLibrary/2d3add8596

Btw, if you add a GitHub release then we'll be able to use that as the version instead of a commit:
https://github.com/AndroidDeveloperLB/MaterialPreferenceLibrary/releases

**Comment by AndroidDeveloperLB** [comment]
Doesn't this include the sample inside too?
How do I make it exclude what's not needed?

**Comment by AndroidDeveloperLB** [comment]
The app now has a release and an easy-to-use gradle repo. closing this issue.
